// Paths are relative to `${NEXT_PUBLIC_API_PREFIX}${NEXT_PUBLIC_API_VERSION}` and are served by
// the Hono app in src/server/api. Keep them in sync with the `.route()` chain there.
export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  health: '/health',
  media: {
    sign: '/media/sign',
    delete: (publicId: string) => `/media/${publicId}`,
  },
  siteSettings: {
    public: '/site-settings',
    admin: '/site-settings/admin',
    updateBusinessInfo: '/site-settings/business-info',
    updateContact: '/site-settings/contact',
    updateSocialLinks: '/site-settings/social-links',
    updateBranding: '/site-settings/branding',
    updateHeroMedia: '/site-settings/hero-media',
    updateSeo: '/site-settings/seo',
    updateHomepageHero: '/site-settings/homepage-hero',
    updateHomepageCatalog: '/site-settings/homepage-catalog',
    updateServicesHero: '/site-settings/services-hero',
    updateOurWorkHero: '/site-settings/our-work-hero',
    updateInsurancePage: '/site-settings/insurance-page',
    updateAboutPage: '/site-settings/about-page',
    updateProcessPage: '/site-settings/process-page',
  },
  services: {
    public: '/services',
    adminList: '/services/admin/list',
    detail: (id: string) => `/services/${id}`,
    create: '/services',
    update: (id: string) => `/services/${id}`,
    remove: (id: string) => `/services/${id}`,
    reorder: '/services/reorder',
  },
  projects: {
    public: '/projects',
    featured: '/projects/featured',
    adminList: '/projects/admin/list',
    detail: (id: string) => `/projects/${id}`,
    create: '/projects',
    update: (id: string) => `/projects/${id}`,
    remove: (id: string) => `/projects/${id}`,
    updateStatus: (id: string) => `/projects/${id}/status`,
    reorder: '/projects/reorder',
  },
  testimonials: {
    public: '/testimonials',
    featured: '/testimonials/featured',
    adminList: '/testimonials/admin/list',
    detail: (id: string) => `/testimonials/${id}`,
    create: '/testimonials',
    update: (id: string) => `/testimonials/${id}`,
    remove: (id: string) => `/testimonials/${id}`,
    updateStatus: (id: string) => `/testimonials/${id}/status`,
    reorder: '/testimonials/reorder',
  },
  partnerLogos: {
    public: '/partner-logos',
    adminList: '/partner-logos/admin/list',
    detail: (id: string) => `/partner-logos/${id}`,
    create: '/partner-logos',
    update: (id: string) => `/partner-logos/${id}`,
    remove: (id: string) => `/partner-logos/${id}`,
    reorder: '/partner-logos/reorder',
  },
  homepagePillars: {
    public: '/homepage-pillars',
    adminList: '/homepage-pillars/admin/list',
    detail: (id: string) => `/homepage-pillars/${id}`,
    create: '/homepage-pillars',
    update: (id: string) => `/homepage-pillars/${id}`,
    remove: (id: string) => `/homepage-pillars/${id}`,
    reorder: '/homepage-pillars/reorder',
  },
  homepageCatalogs: {
    public: '/homepage-catalogs',
    adminList: '/homepage-catalogs/admin/list',
    detail: (id: string) => `/homepage-catalogs/${id}`,
    create: '/homepage-catalogs',
    update: (id: string) => `/homepage-catalogs/${id}`,
    remove: (id: string) => `/homepage-catalogs/${id}`,
    reorder: '/homepage-catalogs/reorder',
  },
  homepageProcessSteps: {
    public: '/homepage-process-steps',
    adminList: '/homepage-process-steps/admin/list',
    detail: (id: string) => `/homepage-process-steps/${id}`,
    create: '/homepage-process-steps',
    update: (id: string) => `/homepage-process-steps/${id}`,
    remove: (id: string) => `/homepage-process-steps/${id}`,
    reorder: '/homepage-process-steps/reorder',
  },
  admins: {
    list: '/admins',
    detail: (id: string) => `/admins/${id}`,
    create: '/admins',
    update: (id: string) => `/admins/${id}`,
    resetPassword: (id: string) => `/admins/${id}/password`,
  },
  users: {
    list: '/users',
    create: '/users',
  },
  quotes: {
    submit: '/quotes',
    adminList: '/quotes/admin/list',
    stats: '/quotes/admin/stats',
    detail: (id: string) => `/quotes/${id}`,
    update: (id: string) => `/quotes/${id}`,
    remove: (id: string) => `/quotes/${id}`,
  },
  contacts: {
    submit: '/contacts',
    adminList: '/contacts/admin/list',
    stats: '/contacts/admin/stats',
    detail: (id: string) => `/contacts/${id}`,
    update: (id: string) => `/contacts/${id}`,
    remove: (id: string) => `/contacts/${id}`,
  },
} as const;
