import { boolean, jsonb, pgTable, smallint, text, timestamp, varchar } from 'drizzle-orm/pg-core';

// Singleton config table — exactly one row, always id=1. No indexes needed: every read is a
// primary-key lookup on a single-row table.
export const siteSettings = pgTable('site_settings', {
  id: smallint('id').primaryKey().default(1),
  businessName: varchar('business_name', { length: 255 }).notNull(),
  phone: varchar('phone', { length: 50 }).notNull(),
  emergencyPhone: varchar('emergency_phone', { length: 50 }),
  email: varchar('email', { length: 255 }).notNull(),
  address: text('address').notNull(),
  openingHours: text('opening_hours').notNull(),
  googleMapsUrl: varchar('google_maps_url', { length: 1000 }),
  whatsappNumber: varchar('whatsapp_number', { length: 50 }),
  facebookUrl: varchar('facebook_url', { length: 1000 }),
  instagramUrl: varchar('instagram_url', { length: 1000 }),
  tiktokUrl: varchar('tiktok_url', { length: 1000 }),
  linkedinUrl: varchar('linkedin_url', { length: 1000 }),
  logoPublicId: varchar('logo_public_id', { length: 500 }),
  faviconPublicId: varchar('favicon_public_id', { length: 500 }),
  heroVideoPublicId: varchar('hero_video_public_id', { length: 500 }),
  heroFallbackImagePublicId: varchar('hero_fallback_image_public_id', { length: 500 }),
  heroVideoEnabled: boolean('hero_video_enabled').notNull().default(false),
  metaTitle: varchar('meta_title', { length: 255 }),
  metaDescription: varchar('meta_description', { length: 500 }),
  ogImagePublicId: varchar('og_image_public_id', { length: 500 }),
  twitterHandle: varchar('twitter_handle', { length: 50 }),
  heroEyebrow: varchar('hero_eyebrow', { length: 200 }),
  heroHeadlineLine1: varchar('hero_headline_line1', { length: 100 }),
  heroHeadlineLine2: varchar('hero_headline_line2', { length: 100 }),
  heroHeadlineAccent: varchar('hero_headline_accent', { length: 100 }),
  heroSubtext: text('hero_subtext'),
  trustBadge1Title: varchar('trust_badge1_title', { length: 100 }),
  trustBadge1Subtitle: varchar('trust_badge1_subtitle', { length: 150 }),
  trustBadge2Title: varchar('trust_badge2_title', { length: 100 }),
  trustBadge2Subtitle: varchar('trust_badge2_subtitle', { length: 150 }),
  trustBadge3Title: varchar('trust_badge3_title', { length: 100 }),
  trustBadge3Subtitle: varchar('trust_badge3_subtitle', { length: 150 }),
  trustBadge4Title: varchar('trust_badge4_title', { length: 100 }),
  trustBadge4Subtitle: varchar('trust_badge4_subtitle', { length: 150 }),
  catalogEyebrow: varchar('catalog_eyebrow', { length: 200 }),
  catalogHeadlineLine1: varchar('catalog_headline_line1', { length: 100 }),
  catalogHeadlineAccent: varchar('catalog_headline_accent', { length: 100 }),
  catalogSubtext: text('catalog_subtext'),
  servicesHeroEyebrow: varchar('services_hero_eyebrow', { length: 200 }),
  servicesHeroHeadlineLine1: varchar('services_hero_headline_line1', { length: 100 }),
  servicesHeroHeadlineAccent: varchar('services_hero_headline_accent', { length: 100 }),
  servicesHeroSubtext: text('services_hero_subtext'),
  ourWorkHeroEyebrow: varchar('our_work_hero_eyebrow', { length: 200 }),
  ourWorkHeroHeadlineLine1: varchar('our_work_hero_headline_line1', { length: 100 }),
  ourWorkHeroHeadlineAccent: varchar('our_work_hero_headline_accent', { length: 100 }),
  ourWorkHeroSubtext: text('our_work_hero_subtext'),
  insuranceHeroEyebrow: varchar('insurance_hero_eyebrow', { length: 200 }),
  insuranceHeroLine1: varchar('insurance_hero_line1', { length: 100 }),
  insuranceHeroLine2: varchar('insurance_hero_line2', { length: 100 }),
  insuranceHeroLine3: varchar('insurance_hero_line3', { length: 100 }),
  insuranceHeroSubtext: text('insurance_hero_subtext'),
  insuranceCoordinationTitle: varchar('insurance_coordination_title', { length: 160 }),
  insuranceCoordinationSubtext: text('insurance_coordination_subtext'),
  insuranceFeatures: jsonb('insurance_features').$type<{ title: string; description: string }[]>(),
  insuranceStepsEyebrow: varchar('insurance_steps_eyebrow', { length: 100 }),
  insuranceStepsTitle: varchar('insurance_steps_title', { length: 160 }),
  insuranceSteps: jsonb('insurance_steps').$type<{ label: string; description: string }[]>(),
  insuranceCtaLine1: varchar('insurance_cta_line1', { length: 100 }),
  insuranceCtaAccent: varchar('insurance_cta_accent', { length: 100 }),
  insuranceCtaSubtext: text('insurance_cta_subtext'),
  insuranceDisclaimer: text('insurance_disclaimer'),
  aboutHeroEyebrow: varchar('about_hero_eyebrow', { length: 200 }),
  aboutHeroLine1: varchar('about_hero_line1', { length: 100 }),
  aboutHeroAccent1: varchar('about_hero_accent1', { length: 100 }),
  aboutHeroLine2: varchar('about_hero_line2', { length: 100 }),
  aboutHeroAccent2: varchar('about_hero_accent2', { length: 100 }),
  aboutHeroImagePublicId: varchar('about_hero_image_public_id', { length: 255 }),
  aboutHeritageTitle: varchar('about_heritage_title', { length: 160 }),
  aboutHeritageText: text('about_heritage_text'),
  aboutHeritageStat1Value: varchar('about_heritage_stat1_value', { length: 40 }),
  aboutHeritageStat1Label: varchar('about_heritage_stat1_label', { length: 80 }),
  aboutHeritageStat2Value: varchar('about_heritage_stat2_value', { length: 40 }),
  aboutHeritageStat2Label: varchar('about_heritage_stat2_label', { length: 80 }),
  aboutHeritageImagePublicId: varchar('about_heritage_image_public_id', { length: 255 }),
  aboutHeritageQuote: text('about_heritage_quote'),
  aboutTeamTitle: varchar('about_team_title', { length: 160 }),
  aboutTeamSubtext: text('about_team_subtext'),
  aboutTeamMembers: jsonb('about_team_members').$type<{ name: string; role: string; imagePublicId: string | null }[]>(),
  aboutStandardsEyebrow: varchar('about_standards_eyebrow', { length: 100 }),
  aboutStandardsTitle: varchar('about_standards_title', { length: 160 }),
  aboutStandardsImagePublicId: varchar('about_standards_image_public_id', { length: 255 }),
  processPageEyebrow: varchar('process_page_eyebrow', { length: 200 }),
  processPageTitle: varchar('process_page_title', { length: 160 }),
  processPageSubtext: text('process_page_subtext'),
  aboutStandardsItems: jsonb('about_standards_items').$type<{ title: string; description: string }[]>(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export type SiteSettings = typeof siteSettings.$inferSelect;
export type NewSiteSettings = typeof siteSettings.$inferInsert;
