import type { CustomerRecord, StaffMember, DashboardMetrics } from './types';

export const INITIAL_CUSTOMERS: CustomerRecord[] = [
  {
    id: 'JOB-2026-00421',
    contactName: 'James Murphy',
    phone: '+353 87 234 9102',
    email: 'james.murphy@gmail.com',
    address: '42 Sandymount Avenue, Dublin 4, Ireland',
    regNumber: '241-D-12345',
    vehicleModel: 'Porsche 911 Carrera',
    year: 2024,
    vin: 'WP0ZZZ99ZPS128910',
    paintCode: 'Porsche C9A Pure White',
    serviceScope: 'Structural body repair, heated downdraft clearcoat bake',
    channel: 'Website Form',
    status: 'Work in Progress',
    currentMilestone: 4,
    estimateValue: 4250,
    assignedTech: "Liam O'Rourke",
    bay: 'Booth 1 • Blowtherm Bake',
    progressPercent: 85,
    dueTarget: 'Today 16:30',
    photos: ['/assets/marketing/project-porsche-911-before.jpg', '/assets/marketing/project-porsche-911-after.jpg'],
    customNotes: [
      'Customer dropped off vehicle at 08:30 via recovery.',
      'Allianz Direct Billing claim #ALZ-9418 approved.',
      'Blowtherm bake cycle running at 68°C.',
    ],
    createdAt: '2026-09-02T08:30:00Z',
    updatedAt: '2026-09-04T11:15:00Z',
  },
  {
    id: 'JOB-2026-00422',
    contactName: 'Sarah Kelly',
    phone: '+353 86 982 3144',
    email: 'sarah.kelly@outlook.ie',
    address: '15 Foxrock Manor, Dublin 18, Ireland',
    regNumber: '221-D-8491',
    vehicleModel: 'BMW 3 Series M-Sport',
    year: 2022,
    vin: 'WBA5R7201NFA34912',
    paintCode: 'BMW C31 Portimao Blue',
    serviceScope: 'Chassis laser realignment and driver side doors replacement',
    channel: 'Direct Phone Call',
    status: 'Work in Progress',
    currentMilestone: 4,
    estimateValue: 3100,
    assignedTech: "Declan O'Sullivan",
    bay: 'Bay 3 • Celette Jig Bench',
    progressPercent: 45,
    dueTarget: 'Tomorrow 12:00',
    photos: ['/assets/marketing/project-bmw-3-series-before.jpg', '/assets/marketing/project-bmw-3-series-after.jpg'],
    customNotes: [
      'Side impact collision in Dun Laoghaire.',
      'AXA Insurance loss adjuster inspected on-site.',
      'Celette jig pulling laser calibrated within 0.1mm OEM tolerance.',
    ],
    createdAt: '2026-09-01T14:20:00Z',
    updatedAt: '2026-09-04T09:40:00Z',
  },
  {
    id: 'JOB-2026-00423',
    contactName: 'David Ryan',
    phone: '+353 85 441 2983',
    email: 'david.ryan@techireland.com',
    address: '88 Clontarf Road, Dublin 3, Ireland',
    regNumber: '242-D-9012',
    vehicleModel: 'Audi RS6 Avant Carbon Edition',
    year: 2024,
    vin: 'WAUZZZF28RA091823',
    paintCode: 'Audi Nardo Grey (LY7C)',
    serviceScope: 'Aluminum wing reconstruction and dynamic ADAS radar realignment',
    channel: 'WhatsApp',
    status: 'Approved',
    currentMilestone: 3,
    estimateValue: 5600,
    assignedTech: 'Siobhan Gallagher',
    bay: 'Bay 2 • Body Assembly',
    progressPercent: 60,
    dueTarget: 'Today 18:00',
    photos: ['/assets/marketing/project-audi-rs6-before.jpg', '/assets/marketing/project-audi-rs6-after.jpg'],
    customNotes: [
      'Customer sent damage video via WhatsApp hotline.',
      'OEM carbon components dispatched from Audi Germany.',
    ],
    createdAt: '2026-08-30T10:00:00Z',
    updatedAt: '2026-09-04T10:30:00Z',
  },
  {
    id: 'JOB-2026-00424',
    contactName: 'Cormac Walsh',
    phone: '+353 87 119 4022',
    email: 'cormac.walsh@construct.ie',
    address: 'Unit 12, Sandyford Business Park, Dublin, Ireland',
    regNumber: '211-D-3341',
    vehicleModel: 'Land Rover Defender 110',
    year: 2021,
    vin: 'SALWR2V45MA781923',
    paintCode: 'Pangea Green (LRC2371)',
    serviceScope: 'Commercial fleet structural restoration & NCT compliance prep',
    channel: 'Walk-ins',
    status: 'Quote Sent',
    currentMilestone: 3,
    estimateValue: 2850,
    assignedTech: 'Liam Murphy',
    bay: 'Bay 4 • Laser Rig',
    progressPercent: 30,
    dueTarget: 'Tomorrow 15:00',
    photos: ['/assets/marketing/project-defender-before.jpg'],
    customNotes: [
      'Walked in without appointment; emergency front bull-bar and steering check.',
      'Commercial tax claim submitted to Zurich.',
    ],
    createdAt: '2026-09-03T11:15:00Z',
    updatedAt: '2026-09-04T08:00:00Z',
  },
  {
    id: 'JOB-2026-00425',
    contactName: 'Patrick Byrne',
    phone: '+353 86 312 9011',
    email: 'pbyrne@capital.ie',
    address: '27 Fitzwilliam Square, Dublin 2, Ireland',
    regNumber: '231-D-7729',
    vehicleModel: 'Mercedes-AMG C63 S',
    year: 2023,
    vin: 'WDD2050872F981245',
    paintCode: 'Selenite Grey Magno (297)',
    serviceScope: 'Matte paint scuff correction & 9H ceramic coating application',
    channel: 'Email',
    status: 'Completed',
    currentMilestone: 5,
    estimateValue: 1950,
    assignedTech: 'Mark H.',
    bay: 'Detox Bay • Handover',
    progressPercent: 100,
    dueTarget: 'Today 14:00',
    photos: ['/assets/marketing/service-scratch-repair.jpg'],
    customNotes: [
      'Final 42-point QC signed off by workshop manager.',
      'Payment settled in full via direct bank transfer.',
      'Vehicle valeted and sanitised for customer handover.',
    ],
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'JOB-2026-00426',
    contactName: 'Aisling Dunne',
    phone: '+353 87 654 3210',
    email: 'aisling.dunne@gmail.com',
    address: '9 Blackrock Main Street, Dublin, Ireland',
    regNumber: '241-D-5512',
    vehicleModel: 'Tesla Model Y Performance',
    year: 2024,
    vin: 'XP7YGCEJ1RB102938',
    paintCode: 'Solid Black (PBSB)',
    serviceScope: 'Paintless Dent Removal on rear quarter crease',
    channel: 'Facebook / Social',
    status: 'New',
    currentMilestone: 1,
    estimateValue: 480,
    dueTarget: 'In Review',
    progressPercent: 0,
    photos: ['/assets/marketing/service-dent-repair.jpg'],
    customNotes: [
      'Inquiry received from Instagram direct message.',
      'Zero paint damage reported; ideal for same-day PDR.',
    ],
    createdAt: '2026-09-04T07:45:00Z',
    updatedAt: '2026-09-04T07:45:00Z',
  },
  {
    id: 'JOB-2026-00427',
    contactName: 'Brian Connelly',
    phone: '+353 89 201 8847',
    email: 'bconnelly@motors.ie',
    address: '14 Malahide Road, Dublin, Ireland',
    regNumber: '202-D-1549',
    vehicleModel: 'Volkswagen Golf R',
    year: 2020,
    vin: 'WVWZZZAUZLW091823',
    paintCode: 'Lapiz Blue Metallic (LD5K)',
    serviceScope: 'Front bumper respray and diamond-cut alloy refurbishment',
    channel: 'Website Form',
    status: 'Contacted',
    currentMilestone: 2,
    estimateValue: 980,
    dueTarget: 'Waiting Estimate Response',
    progressPercent: 15,
    photos: ['/assets/marketing/service-paintwork.jpg'],
    customNotes: [
      'Assessed customer photos submitted via online portal.',
      'Spoke with Brian at 09:30; sent inspection time slot.',
    ],
    createdAt: '2026-09-04T08:15:00Z',
    updatedAt: '2026-09-04T09:35:00Z',
  },
  {
    id: 'JOB-2026-00428',
    contactName: 'Niamh Fitzpatrick',
    phone: '+353 85 911 0244',
    email: 'niamh.f@dublinlaw.ie',
    address: '6 Merrion Square, Dublin 2, Ireland',
    regNumber: '232-D-4190',
    vehicleModel: 'Volvo XC90 T8 Recharge',
    year: 2023,
    vin: 'YV4BR02U6P1209384',
    paintCode: 'Crystal White Pearl (707)',
    serviceScope: 'Rear tailgate collision repair & parking sensor replacement',
    channel: 'Direct Phone Call',
    status: 'Waiting for Response',
    currentMilestone: 3,
    estimateValue: 2400,
    dueTarget: 'Awaiting Insurer Sign-off',
    progressPercent: 20,
    photos: ['/assets/marketing/service-crash-repair.jpg'],
    customNotes: [
      'Estimate sent to FBD Insurance desk.',
      'Waiting for assessor callback regarding OEM tailgate pricing.',
    ],
    createdAt: '2026-09-03T16:00:00Z',
    updatedAt: '2026-09-04T08:45:00Z',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'STAFF-01',
    name: "Liam O'Sullivan",
    role: 'Admin',
    email: 'liam@vantageautobody.ie',
    phone: '+353 1 234 5678',
    status: 'On Shift',
    permissions: {
      canManageEnquiries: true,
      canEditJobStatus: true,
      canViewFinancials: true,
      canManageStaff: true,
      canIssueInvoices: true,
    },
  },
  {
    id: 'STAFF-02',
    name: "Liam O'Rourke",
    role: 'Technician',
    email: 'lorourke@vantageautobody.ie',
    phone: '+353 87 501 2291',
    status: 'On Shift',
    assignedBays: ['Booth 1 • Blowtherm', 'Booth 2'],
    permissions: {
      canManageEnquiries: false,
      canEditJobStatus: true,
      canViewFinancials: false,
      canManageStaff: false,
      canIssueInvoices: false,
    },
  },
  {
    id: 'STAFF-03',
    name: 'Siobhan Gallagher',
    role: 'Technician',
    email: 'sgallagher@vantageautobody.ie',
    phone: '+353 86 410 8823',
    status: 'On Shift',
    assignedBays: ['Bay 2 • Body Assembly', 'Bay 3 • Celette'],
    permissions: {
      canManageEnquiries: false,
      canEditJobStatus: true,
      canViewFinancials: false,
      canManageStaff: false,
      canIssueInvoices: false,
    },
  },
  {
    id: 'STAFF-04',
    name: 'Aoife Brennan',
    role: 'Front Desk',
    email: 'aoife@vantageautobody.ie',
    phone: '+353 1 234 5679',
    status: 'Active',
    permissions: {
      canManageEnquiries: true,
      canEditJobStatus: true,
      canViewFinancials: false,
      canManageStaff: false,
      canIssueInvoices: false,
    },
  },
  {
    id: 'STAFF-05',
    name: 'Sean MacNamara',
    role: 'Billing',
    email: 'accounts@vantageautobody.ie',
    phone: '+353 1 234 5680',
    status: 'Active',
    permissions: {
      canManageEnquiries: true,
      canEditJobStatus: false,
      canViewFinancials: true,
      canManageStaff: false,
      canIssueInvoices: true,
    },
  },
];

export const INITIAL_METRICS: DashboardMetrics = {
  totalNewEnquiries: 24,
  activeJobs: 17,
  completedWork: 48,
  pendingQuotesValue: 14850,
  pendingQuotesCount: 18,
  bayUtilizationPercent: 85,
  monthlyRevenue: 84200,
  revenueGrowthPercent: 18.4,
};
